; Evolution types
EV_LEVEL           EQU 1
EV_ITEM            EQU 2
EV_TRADE           EQU 3
EV_HAPPINESS_DAY   EQU 4
EV_HAPPINESS_NIGHT EQU 5
EV_MOSS_ROCK       EQU 6
EV_ICE_ROCK        EQU 7
EV_HAPPINESS       EQU 8


MOSS_ROCK_MAP    EQU ROCK_TUNNEL_1
MOSS_ROCK_X      EQU $20
MOSS_ROCK_Y      EQU $3
MOSS_ROCK_WIDTH  EQU 6
MOSS_ROCK_HEIGHT EQU 6

ICE_ROCK_MAP    EQU ROUTE_3
ICE_ROCK_X      EQU 14
ICE_ROCK_Y      EQU 6
ICE_ROCK_WIDTH  EQU 2
ICE_ROCK_HEIGHT EQU 2
